/** Per-chapter reading material for /book/chapters/[n], drawn from the
 * abridged edition (Agentic AI for Actuaries: A Concise Primer, SSSIA
 * 2026).
 *
 * This is the *excerpt tier* and it is deliberately bounded: each chapter
 * contributes its opening vignette and closing paragraph verbatim, plus a
 * condensed summary of the argument in between. The full abridged chapter
 * — roughly a thousand words each — is not in this repository and must not
 * be added to it; it is the gated download offered on /book/primer. */

export type ChapterContent = {
  /** The manuscript's sub-title line, where the chapter carries one. */
  subtitle?: string;
  /** Opening scene, verbatim. Every chapter of the book opens with one. */
  vignette: string;
  /** Condensed argument, 3 paragraphs. */
  summary: string[];
  /** Closing framing paragraph, verbatim. */
  closing: string;
  /** One sharp line for pull-quote and social preview. */
  pullQuote: string;
};

export const CHAPTER_CONTENT: Record<number, ChapterContent> = {
  1: {
    subtitle: "What Actuaries Need to Know",
    vignette:
      "It is the first Monday of January, and a pricing actuary at a mid-size composite insurer sits down to renew a commercial property portfolio of 340 accounts. By Friday, working in the traditional way, she has a preliminary indication for sixty of them. Down the corridor, a colleague using AI-assisted extraction and first-pass analysis has the full portfolio ready for peer review by Tuesday afternoon. The difference is not talent. Both hold the same fellowship qualification. The difference is the system.",
    summary: [
      "Artificial intelligence is not one technology but a family of techniques with different histories, different assumptions, and very different reliability profiles. A pricing actuary using a generalised linear model is already using machine learning; a claims handler triaging photographs of vehicle damage is using a convolutional neural network; a reserving actuary asking a chatbot for loss-development commentary is using a large language model. The field arrived in waves — symbolic rule systems in the 1950s and 1960s, learning from data from the late 1980s, deep neural networks from around 2012, and transformers and large language models from 2017 onward — and each wave added capability without retiring its predecessor. A working actuarial stack today may use all four at once.",
      "Three pressures make the question urgent rather than academic. Regulatory complexity has increased materially since IFRS 17 took effect for reporting periods beginning on or after 1 January 2023, alongside the Solvency II review in the European Union, Long-Duration Targeted Improvements under ASC 944 for United States life insurers from 2023, and the digital reporting expectations of the Insurance Regulatory and Development Authority of India. The volume of structured and unstructured data available to actuaries has grown by orders of magnitude in a decade. And competitive cycle time has tightened. The taxonomy matters because reliability varies across it: a rule-based check is predictable, a gradient-boosted tree is reliable on data resembling its training set, and a large language model is fluent, often plausible, and capable of confident outputs that are simply wrong.",
      "The question the authors are asked most often is whether AI will replace actuaries, and their answer is structural rather than predictive. Insurance regulation requires a named, qualified individual to sign opinions and certifications: the Appointed Actuary in India, the Actuarial Function Holder under Solvency II, the signing actuary attaching their reputation to a Statement of Actuarial Opinion in the United States. Each bears personal professional liability no software can absorb. The productive framing is partnership — AI takes the repetitive, data-intensive, mechanical work; the actuary retains judgment, communication, and accountability — with one caveat the spreadsheet analogy misses. Spreadsheets did not produce confident, plausible, occasionally wrong outputs. AI does, and the judgment required to validate those outputs is itself a new actuarial skill.",
    ],
    closing:
      "What this chapter has done is set the frame: AI is a family of techniques, the regulatory and data context makes adoption non-optional for most actuarial functions, and the partnership model rests on a structural constraint that will outlast any specific technology. The chapters that follow build the conceptual machinery — machine learning, deep learning, language models, agents, memory, planning — required to act on this frame.",
    pullQuote:
      "No AI system can sign a Statement of Actuarial Opinion. No algorithm can bear professional liability. These are structural constraints, not temporary ones.",
  },

  2: {
    vignette:
      "A reserving actuary at a general insurer notices that the chain ladder estimate for a recent accident year is drifting upward, while the Bornhuetter-Ferguson estimate is more stable. She would like a third opinion. A gradient-boosted model trained on twenty years of triangle data offers one, conditional on similar economic and operational regimes. The model is not a replacement for either method. It is a structured way to compress prior data into a comparable estimate, with known limits.",
    summary: [
      "An actuary who has built a mortality table has already done machine learning in the precise sense: fit a model to data, use it to predict, validate on data not used in fitting, deploy with assumptions documented. Machine learning extends that practice in three directions — richer model families such as tree ensembles and neural networks that capture interactions generalised linear models struggle with; far larger feature sets, including features extracted from text and images; and a formalised workflow of feature engineering, training, validation, deployment and monitoring that is recognisably the actuarial control cycle under different terminology.",
      "Supervised learning is the workhorse, splitting into regression problems that predict a continuous quantity such as loss ratio and classification problems that predict a category such as lapse or persist. Unsupervised learning has no target variable and looks for structure — clustering policyholders, or compressing correlated features. Reinforcement learning, which learns by acting and receiving rewards, is the most distant from actuarial practice and still uncommon in production. The central failure mode is overfitting, the machine-learning analogue of an assumption set that fits history and fails to project forward, and the remedies are familiar: enough data, held-out validation and test sets, a preference for simpler models at comparable performance.",
      "Model evaluation is where actuarial training transfers most directly. Accuracy is misleading on imbalanced data — a fraud model that predicts 'not fraud' everywhere scores ninety-nine per cent on a one-per-cent fraud rate and is useless — which actuaries recognise immediately as the reason a base-rate-only loss model is uninformative. Precision, recall, area under the ROC curve and, separately, calibration are the metrics that matter. Machine learning does not displace GLMs: for pricing under regulatory scrutiny in the United Kingdom or the European Union, GLMs remain the production standard for interpretability. The binding limitation is that these techniques assume the future resembles the past in the relevant respects, which is exactly the judgment the actuary must supply.",
    ],
    closing:
      "The capability of these techniques is real. The limitation is that they depend on the future resembling the past in the relevant respects. A lapse model trained on 2015 to 2019 data will likely under-predict lapses in a high-inflation environment. The actuarial habit of stress-testing assumptions and considering regime changes is exactly what machine learning models need around them.",
    pullQuote:
      "An actuary who has built a mortality table has already done machine learning, in the precise sense of fitting a model to data and using it to make predictions.",
  },

  3: {
    vignette:
      "A property and casualty insurer wants to estimate vehicle damage from photographs submitted through a mobile app. A traditional rule-based system cannot extract a number from an image. A convolutional neural network, trained on photographs paired with adjuster estimates, can produce an indicative figure within ten per cent of human assessment in around eighty per cent of cases. The remaining twenty per cent still requires human review. The technology shifts the workflow; it does not eliminate it.",
    summary: [
      "A neural network is a stack of mathematical functions that transform an input into an output. Each layer multiplies the previous layer's output by a matrix of weights, adds a bias, and applies a non-linear activation. Stacked deep enough, with weights learned from data, the construction approximates functions of remarkable complexity; 'deep' refers simply to the number of layers. Training is gradient descent: a loss function compares prediction to truth, backpropagation computes the gradient of that loss with respect to every weight, and each weight is nudged in the direction that reduces it. For an actuary the analogy is iterative assumption-setting — reviewing ultimate-loss estimates against subsequent development and adjusting method — differing chiefly in scale.",
      "Three architectures matter for actuarial applications. Feedforward networks suit tabular data such as claims records and policyholder attributes, though gradient-boosted trees often outperform them there. Convolutional networks, designed for spatial data, underpin image-based damage assessment, satellite imagery for crop and property risk, and medical imaging relevant to health insurance; their weakness is a heavy data appetite and vulnerability to inputs outside their training distribution. Recurrent networks, including LSTM and GRU variants, handle sequences such as development triangles and policyholder behaviour over time, though transformers have largely superseded them.",
      "The attention mechanism, introduced in 2017 and formalised in the transformer architecture, let networks weight different parts of their input when producing each part of their output without the sequential bottleneck that limited recurrent networks — the innovation that made everything later in the book possible. Deep learning's strengths are pattern recognition in raw inputs, scaling with data and compute, and transfer from one large dataset to a related task. Its limitations are equally structural: it is data-hungry, computationally expensive, opaque in ways a regulator or court would not accept, and it fails distinctively — a confidently misclassified image, a fluent citation to a non-existent paper. These are characteristic failure modes of the architecture, not bugs awaiting a patch.",
    ],
    closing:
      "For actuarial work, the practical implication is selectivity. Use deep learning where its strengths align with the problem — image analysis, free-text processing, large-scale pattern detection — and where the cost of wrong outputs is bounded by downstream human review. Avoid it where interpretability is regulatory or where the available training data is small.",
    pullQuote:
      "These are not bugs that will be patched; they are characteristic failure modes of the architecture.",
  },

  4: {
    vignette:
      "A health insurance underwriter receives a hundred-page broker submission for a large group account. Reading it carefully will take half a day. A large language model, given the document and a structured extraction prompt, produces a one-page summary with risk factors flagged in under a minute. The underwriter still reviews the original on the cases the model flags, but the bulk of the reading load shifts. The capability is real. So is the requirement to verify what the model produces.",
    summary: [
      "Before large language models, natural language processing was a collection of narrow techniques — tokenisation, part-of-speech tagging, named entity recognition, sentiment analysis — each requiring its own model and training data. The transformer changed the economics. A transformer trained on hundreds of billions of words with the simple objective of predicting the next token learned representations of language that transferred to almost any downstream task. The first generation, BERT and its variants from 2018, served classification and extraction; the second, from GPT-3 in 2020 onward, was generative and could be conditioned on instructions, examples, or context.",
      "Three properties matter for actuarial work. These models are general: the same model, differently prompted, summarises a regulatory filing, drafts a memo, extracts structured data from a claims note, or answers a domain question. They exhibit emergent abilities that appeared as scale increased. And they are fluent — an asset, because drafts are usable starting points, and a hazard, because incorrect output is not flagged by awkward phrasing. That hazard has a name. Hallucination is not random error but a structural consequence of the training objective: the model is optimised to produce text resembling its training data, so plausibility is the design criterion, not truth. It has no internal mechanism to flag when it is generating from a sparse or wrong region of its training distribution.",
      "The capability that makes these models genuinely useful in actuarial work is text-to-structured-data conversion. Insurance generates large volumes of unstructured text — broker submissions, claims notes, underwriting narratives, regulatory filings, contract wordings — and extraction has historically required manual labour or brittle templates. Given a clear prompt and a target schema, a language model extracts structured fields at a quality that approaches and sometimes exceeds template systems, at a scale manual extraction cannot match. The strategic framing for actuarial leaders is therefore not 'should we deploy a chatbot' but: where in our existing workflows do we manipulate text, and what becomes feasible if that manipulation costs an order of magnitude less?",
    ],
    closing:
      "The chapters that follow take this general capability and develop the disciplines required to use it well. Chapter 5 covers prompting, the primary interface to a large language model. Chapter 6 covers retrieval, the technique that grounds model outputs in authoritative documents. Chapter 7 covers fine-tuning. Chapter 8 covers the architectural decisions required to move from a chatbot demo to a production actuarial system.",
    pullQuote:
      "Plausibility is the design criterion, not truth.",
  },

  5: {
    vignette:
      "A reserving actuary asks a large language model to draft IFRS 17 disclosure narrative for a quarter's results. The first attempt produces vague paragraphs that could fit any insurer in any quarter. After three iterations, adding the specific accounting policy choices, the relevant standards paragraphs, the data tables, and a worked example of the desired tone, the same model produces a draft that requires only minor edits. The capability lived in the model. Accessing it required learning to ask.",
    summary: [
      "Prompting is the primary interface between an actuary and a large language model, and its economics are unusually favourable: a well-designed prompt converts a general-purpose model into a competent specialist at near-zero marginal cost, with no training required. A useful prompt has six elements — role, context, instruction, format, constraints, and examples. The role establishes perspective; the context supplies data and definitions; the instruction states the task; the format specifies whether the output should be prose, table, JSON or bullets; the constraints state what the model must not do, such as inventing figures or concealing uncertainty; the examples show completed instances. Not every prompt needs all six, but most production prompts in actuarial settings carry at least four.",
      "Several techniques have stable names. Zero-shot prompting supplies no examples; few-shot supplies one to five; chain-of-thought asks the model to reason step by step before answering, improving accuracy on multi-step problems at the cost of length and latency; self-consistency runs the same prompt repeatedly and aggregates. For most actuarial applications, careful zero-shot or few-shot prompting with chain-of-thought reasoning is sufficient. Structured output is a separate skill and the backbone of the agent architectures in Part III: 'Summarise this claim' is vague, while 'Return a JSON object with fields claim_id, reported_date, cause_code, severity_estimate, confidence' is precise. Prompt chaining decomposes a complex task into a sequence of simpler prompts and is the bridge to agentic AI — an agent is, in part, a system that decides which prompt to run next.",
      "The pitfalls are worth naming because they have materialised in production. The most common is over-reliance: fluent output taken at face value, with errors propagating downstream, compounded by confirmation bias when the prompt steers the model toward an expected answer. The remedy is structural — separate generation from validation, build evaluation harnesses that check outputs against ground truth on a sample, and require human review at consequential decision points. A subtler pitfall is prompt drift: a prompt that worked against one model version may behave differently against its successor, and models are updated, sometimes silently. Production prompt libraries should be versioned and re-evaluated against a fixed test set whenever the underlying model changes.",
    ],
    closing:
      "The capability that prompting unlocks is real. The limitation is that prompting alone does not give the model access to authoritative documents, current data, or the ability to call actuarial calculations. Those capabilities require the techniques developed in the next three chapters: retrieval-augmented generation, fine-tuning, and the architectural patterns that lift a chatbot into a production system.",
    pullQuote:
      "The same discipline actuaries apply to model assumptions applies, with no modification, to prompts.",
  },

  6: {
    vignette:
      "An actuary working on an IFRS 17 query asks a chatbot for guidance on the contractual service margin under a specific transition method. The model produces a confident answer, citing a paragraph number that does not exist in the standard. A retrieval-augmented system, given the same query, first searches a curated index of the IFRS 17 standard, locates the relevant paragraphs, and asks the model to answer using only those passages. The second answer is correct, traceable, and refusable when the retrieved context is insufficient.",
    summary: [
      "Retrieval-augmented generation is the architectural response to hallucination. Rather than relying on the model's parametric memory, the system retrieves relevant documents from an authoritative source at query time and instructs the model to ground its answer in them. The architecture separates knowing the documents, a retrieval problem, from producing fluent prose grounded in them, a generation problem. The pipeline has three stages: retrieval returns the chunks most relevant to the query, augmentation inserts them into the prompt, and generation produces the answer using only that context. The model can also be instructed to refuse when context is insufficient — operationally important for actuarial applications under regulatory scrutiny.",
      "Retrieval is the substantive engineering challenge. Keyword search works when actuarial terminology is precise and queries match document language, but struggles across synonyms — 'expected loss' versus 'ultimate loss', 'Bornhuetter-Ferguson' versus 'BF method'. Vector search embeds queries and documents into a space where semantic similarity is proximity. Hybrid search combines both and is generally more robust, particularly for actuarial documents where exact-match terms such as regulation numbers coexist with conceptual content. What to index is itself a governance question: regulatory documents are obvious candidates but go stale, while internal methodology notes, peer review templates and prior reports are higher-value because they capture house conventions no public model has seen.",
      "Chunking is the unglamorous but consequential decision of how to split documents. Naive fixed-token chunking works for prose and fails on actuarial documents containing tables, formulas and cross-references: a formula split mid-line is uninterpretable, a table split between header and body is misleading. The remedy is structural chunking that respects document hierarchy and keeps tables intact. Evaluation must cover both stages separately — recall at k and mean reciprocal rank for retrieval; faithfulness, answer relevance and context relevance for generation — because a poor answer can come from either, and the remedies differ. The named failure modes are retrieval failure, generation failure, and stale-context failure, each with its own fix.",
    ],
    closing:
      "The capability is genuine; the engineering is non-trivial. A production-grade RAG system requires sustained attention to index curation, chunking strategy, retrieval quality, prompt design, and evaluation. The investment is worthwhile when the alternative is either no automated answer or an answer that cannot be cited.",
    pullQuote:
      "The value is not the model's general fluency. It is the retrieval layer that makes the answer auditable.",
  },

  7: {
    vignette:
      "A reinsurance company finds that a general-purpose model produces treaty summaries that are accurate but tonally wrong, too colloquial for a document that goes to senior underwriters. After fine-tuning the model on three hundred pairs of treaty documents and house-style summaries, the same model produces summaries that read as if written by an experienced cedant analyst. The factual accuracy improves marginally; the stylistic match improves substantially. The investment was worthwhile because the volume of summaries justified the training cost.",
    summary: [
      "Fine-tuning continues the training of a pre-trained model on a smaller, task-specific dataset, biasing its responses toward the terminology, formats and reasoning styles in that data. It is more invasive than prompting and more expensive than retrieval, and the decision framework is short: most actuarial tasks do not need it. Fine-tuning becomes attractive in three situations — style adherence at scale, where the task is high-volume and the desired output style is distinctive; vocabulary specialisation, where the domain uses terms the general model misreads, confusing 'loss ratio' with 'loss function' or 'reserve' with the verb; and latency or cost optimisation, where a smaller fine-tuned model matches a larger one on the specific task at lower cost per call.",
      "Transfer learning makes the economics work. Because the base model has already absorbed billions of words, useful fine-tuning often needs only a few hundred to a few thousand high-quality examples. Data preparation is where most of the practical effort sits, and quality dominates quantity: a few hundred carefully curated instruction-response pairs usually outperform thousands of mediocre ones. The examples must be representative of the production input distribution, internally consistent, and free of errors the actuary does not want propagated. Constructing the dataset is itself an actuarial exercise — it requires deciding what the desired behaviour is with enough specificity that examples can be written.",
      "Full fine-tuning updates every weight and costs the most. Parameter-efficient methods — Low-Rank Adaptation and its quantised variant QLoRA — update a small fraction of weights at results often indistinguishable from full fine-tuning, and are the practical choice for most actuarial use cases. Evaluation asks a specific question: does the fine-tuned model beat the base model with a well-designed prompt, on a held-out test set? The characteristic risks are catastrophic forgetting, bias amplification where training data reflects historical decisions future practice intends to revise, and overfitting on small datasets. Governance is where regulators are beginning to ask questions: a fine-tuned model is a custom model, and documentation requirements approach those of conventional actuarial models.",
    ],
    closing:
      "The capability of fine-tuning is real and useful in specific situations. The cost is non-trivial: data preparation, training infrastructure, evaluation harness, and ongoing governance. The decision to fine-tune should follow rather than precede an honest assessment of what prompting and retrieval cannot deliver.",
    pullQuote:
      "Each of these is mitigable with careful data preparation, conservative training settings, and rigorous evaluation, but none can be eliminated by hope.",
  },

  8: {
    vignette:
      "A reserving team's pilot AI assistant works beautifully on the demo machine. Six months later, when the team tries to use it for the quarterly close, it fails: the data sources have changed, the model behind the chatbot has been updated, the prompts no longer produce the expected format, and nobody knows whether the outputs being produced are correct. The gap between a working notebook and a production system is not technical sophistication. It is architecture, monitoring, and governance.",
    summary: [
      "A chatbot is a model with a user interface. A production actuarial AI system is a model embedded in a pipeline, with data inputs from authoritative sources, structured outputs to downstream systems, monitoring of behaviour over time, and human oversight at consequential decision points. Underestimating that difference is the most common cause of pilot failure. APIs are the mechanism by which the system reaches a model: consuming a frontier model does not require running it locally, but it does require a provider contract, authentication, and the ability to handle the latency and rate limits the API enforces, at a cost per call scaled to input and output size.",
      "Data pipelines are the actuarial side of the architecture, and the unglamorous majority of the engineering effort. Most actuarial data lives in formats that predate AI — fixed-width files, mainframe extracts, spreadsheets with implicit structure — and moving it into usable form is where the work is. Data quality, lineage and freshness become AI quality, lineage and freshness. Orchestration is the layer coordinating multiple components: retrieval against a methodology library, a model call to draft commentary, a structured-output validator, a downstream filing step. Orchestration is the precursor to agentic AI, which is a more autonomous form of it, where the system decides what to do next rather than following a fixed sequence.",
      "Security and compliance constrain the architecture before any AI component is designed. Insurance data is sensitive, and regulators including the Information Commissioner's Office under UK GDPR, European authorities under GDPR, and the Insurance Regulatory and Development Authority of India impose specific processing requirements. Production architectures answer them through contractual provisions with model providers, data minimisation, redaction before processing, and audit trails of every model interaction — none of them optional. Cost management is likewise architectural, addressed through caching, semantic caching, tiered routing and prompt compression. The transition from prototype to production demands reproducibility, monitoring, versioning, human-in-the-loop checkpoints and rollback — familiar disciplines applied to systems whose third-party model may be updated without notice.",
    ],
    closing:
      "What this chapter has done is establish the architectural vocabulary required before agents become useful. Part III takes up agentic AI proper, beginning with the question of what makes a system \"agentic\" and how an agent differs from the orchestrated pipelines described here.",
    pullQuote:
      "An architecture that supports these requirements is not a constraint on AI deployment; it is the precondition for deploying AI in regulated actuarial functions at all.",
  },

  9: {
    subtitle: "Principles and Architecture",
    vignette:
      "A traditional script that ingests claims data and produces a development triangle works perfectly until the data file arrives with a renamed column. The script halts. An agent, given the same goal — produce a development triangle — notices the unfamiliar column, reasons about what it likely contains, asks for confirmation if uncertain, completes the task, and reports what it changed. The difference is not in the calculation. It is in how the system handles the situation it was not explicitly programmed for.",
    summary: [
      "An agent is a system that takes a goal, decomposes it into actions, executes those actions using tools, observes the results, and adapts its plan as it proceeds. Three properties distinguish it from everything in the earlier chapters: autonomy, in that the agent decides what to do next within designer-set constraints; goal-directed behaviour, in that actions are evaluated against a stated objective rather than a fixed sequence; and environmental interaction, in that the agent acts through tools and receives feedback that shapes its next action. By this definition a chatbot is not an agent, a retrieval-augmented question-answering system is not an agent, and a robotic process automation script is not an agent — each is useful, and each is either fixed or reactive.",
      "The cognitive loop has five stages. Perception takes in the current state; reasoning interprets it and considers actions; planning sequences those actions toward the goal; action executes a step through a tool; memory retains what has happened so it can inform later decisions. The result of the action becomes new perception, and the loop repeats. Three design patterns dominate practice: ReAct alternates reasoning and action steps and is the simplest and most widely used; Plan-and-Execute separates planning from execution and scales better to complex multi-step tasks; Reflexion adds self-evaluation, producing higher-quality output at the cost of additional model calls.",
      "The judgment an actuary has to make is which tasks warrant agentic flexibility at all. Linear, well-defined workflows — extract from a known document type, perform a known calculation, file the result — are often better served by orchestrated pipelines, because an agent's autonomy is unnecessary there and its failure modes harder to govern. Agents earn their cost on heterogeneous inputs: broker submissions in different formats, claims notes with idiosyncratic structure, regulatory queries spanning multiple frameworks. And agents add failure modes of their own on top of the model's: selecting the wrong tool and producing a wrong result fluently, misinterpreting a tool's output and compounding the error, or looping on an action that fails for a reason it cannot diagnose. The remedies are architectural — step limits, monitoring for repeated failures, structured logging of every tool call, and human review where errors are consequential.",
    ],
    closing:
      "The introduction of agentic AI to actuarial work is at an early stage. The technology is real and useful in specific applications. The maturity of the surrounding governance is, candidly, not yet sufficient for unsupervised deployment in regulated processes. The pattern that has worked in practice is human-in-the-loop agentic AI: agents that handle the bulk of a workflow autonomously, raising flags for human review at the points where actuarial judgment is required.",
    pullQuote:
      "An agent without tools is a chatbot with extra reasoning steps.",
  },

  10: {
    vignette:
      "A reserving agent is asked to compute the net premium reserve for a ten-year term policy on a thirty-five-year-old male non-smoker. Without tools, the language model produces a plausible number from its training data, with no way to verify it. With access to a mortality-table-lookup tool, an interest-discount-function tool, and a present-value-calculation tool, the same agent retrieves the correct mortality rates, applies the correct discount, performs the calculation, and reports a number that can be reproduced from the tools' outputs. The tools are what make the answer trustworthy.",
    summary: [
      "A tool is a function with a defined name, a specified input schema, and a specified output. The agent's model is given descriptions of the available tools and, when it determines one should be called, emits a structured request to invoke it; the tool runs in code the team controls and returns a result the agent folds into its next reasoning step. This mechanism, function calling, is supported natively by current model APIs, and the conceptual shift it produces is significant: the reliability of the system now depends on the reliability of the tools rather than on the model's parametric memory. For actuarial applications that is the difference between an interesting demonstration and a usable production component.",
      "Designing actuarial tools is partly familiar — wrap an existing calculation, lookup or query in a function with a clear interface — but the consumer is an agent rather than a human, and the descriptions matter as much as the implementation. A tool described as 'lookup_mortality' will be called less reliably and on less appropriate inputs than one described as 'Look up the mortality rate for a given sex, age, smoker status, and standard table. Use this when computing pricing or reserving for life products.' The investment in precise descriptions pays returns in reliability that prompt engineering alone cannot match. Tool selection failure is a characteristic failure mode, and the remedies run in order of complexity: keep the tool set small, write distinctive descriptions, give usage examples, and catch selection errors at validation rather than execution.",
      "Error handling is the second characteristic challenge. A naive agent retries a failing call, fails again, and either loops or gives up. Robust designs require tools to return structured errors — error codes, machine-readable categories, recommended next steps — so the agent can retry, fall back, ask for clarification, or escalate. Sandboxing is the discipline of restricting what tools can do: an agent with read access to a claims database is useful, one with write access is dangerous. Tools should grant the minimum capability required, and consequential operations should require human approval, dry-run modes, audit logging and explicit reversibility. Code execution tools are the sharpest case of this trade-off, enormously powerful and enormously risky, and production deployments sandbox them aggressively.",
    ],
    closing:
      "The investment in tool engineering, often greater than the investment in the agent itself, is what determines whether the system is useful in production. A tool's behaviour can change when the underlying system it wraps is updated. A tool's outputs can mislead the agent if its error-handling is incomplete. The next chapter extends from a single agent with tools to coordinated systems of multiple specialised agents.",
    pullQuote:
      "The blast radius of a tool — the set of consequences a single tool call can have — should be understood before the tool is wired into an agent.",
  },

  11: {
    vignette:
      "A reserving review needs three things in sequence: a data analyst who examines the claims triangles for anomalies, a methodology specialist who applies chain ladder and Bornhuetter-Ferguson methods, and a writer who synthesises the findings into a memorandum. A single agent can do all three, slowly and with frequent context loss. Three specialised agents, coordinated by a supervisor, do each task with focus, pass results between them in structured form, and produce a coherent memorandum. The structure mirrors how human teams work for the same reason it works for human teams.",
    summary: [
      "Multi-agent systems are coordinated arrangements of specialised agents collaborating on goals that a single agent would handle inefficiently or not at all. The motivation is twofold: specialisation produces better outputs in narrow domains, and the cognitive load on any single agent — tools to select among, context to hold, decisions to make — scales poorly with task complexity. Four patterns recur. The sequential pipeline passes output from agent to agent and is easiest to debug. The parallel fan-out runs agents simultaneously on independent sub-tasks. Hierarchical delegation has a top-level agent decompose and delegate. The debate or critique pattern has agents argue opposing positions, with a third agent or a human deciding.",
      "The critical distinction is between workflows and teams. A workflow is a fixed sequence of agent calls with predefined inputs and outputs, its orchestration logic encoded by the designer. A team is a more autonomous arrangement where agents communicate, negotiate and allocate work among themselves, with orchestration emerging from their interactions. Workflows are predictable, debuggable and easier to govern; teams are more flexible and harder to reason about. For actuarial applications under regulatory scrutiny, workflows are the right starting point. The supervisor pattern is the workhorse: one agent receives the goal, decides which specialists to invoke and in what order, monitors progress, handles failures and assembles the result.",
      "Communication between agents requires structure. Free-form text is fluent but lossy, and agents passing natural-language messages are prone to drift, where the original goal is gradually distorted across handoffs. Structured handoffs — JSON objects with explicit fields for goal, data, constraints and expected output — are more reliable, and a handoff schema defined per transition supports validation at the boundary. A structured status field attached to every agent message records what was attempted, what was produced, what errors occurred and what confidence attaches, and becomes the basis for automated alerting, aggregate quality monitoring and post-hoc auditing. When agents disagree, the mechanisms available are voting, authority hierarchies, arbitration by a supervisor, or escalation to a human — and for decisions with regulatory or financial consequences, escalation is usually the right answer.",
    ],
    closing:
      "The capabilities of multi-agent systems extend the reach of agentic AI to tasks that a single agent cannot complete reliably. The limitations multiply the limitations of single agents: more components mean more places to fail, more handoffs mean more opportunities for drift, more autonomy means harder governance. The discipline of starting with workflows rather than teams is what separates a multi-agent system that runs in production from one that works only in demonstrations.",
    pullQuote:
      "The agents do the analytical work; the human does the judgment.",
  },

  12: {
    vignette:
      "An experience-study agent is asked to update last quarter's mortality study with the latest data. Without memory, the agent re-derives every parameter from scratch, possibly producing different methodological choices than the prior run. With persistent memory of last quarter's parameters, methods, and judgement calls, the agent retrieves the prior context, applies the same approach, highlights what has changed in the underlying data, and flags any deviations for review. The continuity is what makes the agent useful for ongoing actuarial work rather than only for one-off analyses.",
    summary: [
      "Three horizons of memory matter, and they are best treated as distinct mechanisms rather than one capability. Short-term memory holds the current task's context and is bounded by the model's context window; it is the easiest to provide and the easiest to mismanage, since retaining everything exhausts the window and degrades performance, while summarising requires its own model calls. The discipline is to summarise at consistent boundaries — the completion of a sub-task, the closing of a tool-use loop — rather than at arbitrary intervals. Long-term memory persists across tasks and takes three forms: a vector store for semantically similar prior content, a structured database for definite values such as assumption tables and methodology choices, and a knowledge graph for relationships. For actuarial work structured storage is generally the better first step, because the decisions worth remembering across runs are themselves structured.",
      "Episodic memory records specific past events — a failure mode encountered last quarter, a methodology choice that resolved an ambiguity, a human correction to a draft — and retrieves them when a similar situation recurs. It produces agents that improve over time in a limited sense without retraining, but retrieval depends on imperfect similarity search, and the wrong lesson applied to a superficially similar situation degrades performance rather than improving it. It is the youngest of the three in production and should be approached with caution.",
      "Planning and reasoning are related but distinct. Planning decomposes a goal into a sequence of actions before execution begins, enabling an agent to consider trade-offs, anticipate dependencies and avoid commitments that close off options; a reserving agent planning a quarterly review can sequence data validation, method application, comparison against prior estimates and drafting in an order that respects dependencies. Reasoning evaluates a situation and chooses a next step, often expressed as a reasoning trace — the natural-language sequence of intermediate steps the model produces before committing to an answer. A trace makes an output reviewable and correctable, because a reviewer can find the step where the argument went wrong rather than seeing only the final number. It is worth being precise about what that buys, because the distinction carries real weight in a regulated function: a reasoning trace is the model's narration of its own thinking, generated alongside the answer and no more reliable than the model producing it. What withstands audit is the execution trace — the tools called, the arguments passed, the values returned, and the approvals given. Reasoning traces support review; execution traces are the record. Self-reflection, in which the agent evaluates its own draft before committing, improves quality measurably but is not a substitute for human review on consequential decisions.",
    ],
    closing:
      "The capability that memory, planning, and reasoning together provide is genuine durability: agents that can be deployed for ongoing work, that retain context across runs, that improve in a limited but real sense, and that produce outputs whose derivation can be examined. The limitations remain those of the underlying model: a reasoning trace that is fluently produced but logically flawed is still flawed, and the discipline of independent verification on consequential outputs remains essential.",
    pullQuote:
      "Memory transforms an agent from a system that produces outputs to a system that learns from its work.",
  },

  13: {
    vignette:
      "A commercial property underwriter receives a submission with twenty exposure schedules, three years of loss runs, broker correspondence describing a recent operational change, and a request for indication within forty-eight hours. An agentic assistant extracts and normalises the data, queries internal benchmarks, runs the rating model, flags the deviation between modelled and broker-suggested premium, and produces a structured underwriting recommendation. The underwriter spends her time on the deviation rather than on the extraction. The judgment work survives. The mechanical work compresses.",
    summary: [
      "Pricing and underwriting cycles share a structure across product lines and geographies: gather information about the risk, assess it against the rating framework, produce an indication, negotiate, bind. The variation across submissions has been large enough that fully deterministic automation has rarely worked at scale — the tasks are heterogeneous, the documents messy, and the judgment at the margin is what the underwriter adds. Agentic AI fits this profile precisely because it absorbs heterogeneity in input format while preserving structure in output.",
      "Six applications have established themselves. Automated rating assembles inputs for an existing rating model, which remains the actuarial control point: the agent feeds the model rather than replacing its logic. Underwriting triage pre-screens submissions against authority, flags those outside it, identifies missing information and routes the rest — sequencing the work rather than making the decision. Competitive intelligence monitors public rate filings, competitor announcements and market reports to produce a continuous brief. Dynamic pricing in personal lines and small commercial refreshes assumptions weekly or daily rather than monthly or quarterly. Model validation converts back-testing and sensitivity analysis from an episodic activity into a continuous one. Regulatory compliance checking flags non-compliant filing elements with citations to source provisions.",
      "The bounds matter as much as the capabilities. Agents perform well on extraction and structured-output tasks and less well where the relevant considerations are not in the documents. They handle volume without eliminating the need for judgment on the unusual case. They reduce cycle time while introducing new operational dependencies on model providers, prompt versions and tool integrations. The pattern that works is selective deployment: agents on the high-volume extraction tasks, with explicit human review where pricing decisions are committed. Governance follows the existing regulatory architecture — the UK Financial Conduct Authority for personal lines, the IRDAI product approval framework, the state insurance commissioners in the United States — and an agentic system that participates in pricing inherits every one of those requirements.",
    ],
    closing:
      "An agentic system that participates in pricing inherits the same requirements: documentation of the agent's behaviour, validation of its outputs against held-out cases, monitoring in production for drift, and clear lines of professional accountability for the outputs the system produces. The architecture supports these requirements; it does not produce them automatically.",
    pullQuote:
      "The judgment work survives. The mechanical work compresses.",
  },

  14: {
    vignette:
      "A reserving actuary at a non-life insurer enters the quarterly close with the same agenda as every previous quarter: pull the data, run the methods, reconcile the results, draft the commentary, present to the appointed actuary. An agentic monitor that has been observing claims development continuously through the quarter has already flagged two segments where development is materially off prior pattern, prepared draft analyses with comparison against the chain ladder and Bornhuetter-Ferguson methods, and assembled the supporting tables. The quarterly scramble becomes a quarterly review.",
    summary: [
      "Reserving sits at the intersection of analytical rigour and professional accountability that defines the profession: high-stakes, time-bound, judgement-intensive, with regulatory consequences that follow the actuary individually. Agentic AI is therefore approached carefully here, and where deployed it supports rather than substitutes for the appointed actuary's judgement. Automated reserve estimation applies chain ladder, Bornhuetter-Ferguson, Cape Cod and frequency-severity approaches to the same triangle and produces a structured comparison of estimates and ranges. The agent does not select the method; it presents the alternatives and their results.",
      "Claims triage classifies new claims against routing criteria, extracts relevant facts from free-text notes, and routes to the appropriate handler, compressing time-to-first-action and reducing variance in routing. Fraud detection gains the ability to reason across multiple sources — claims notes, prior claims by the same claimant, permitted external data — and surface patterns single-source models miss; the agent produces investigative leads, not adjudications. Loss development monitoring is among the higher-value applications precisely because the work is naturally continuous: an agent observing monthly development against historical patterns flags deviations that may prove benign or substantive, and the assessment remains the actuary's. Narrative generation for reserving memoranda is the application that most consistently surprises actuaries — the draft is rarely final, but it is rarely useless, and the compression of drafting time is real and measurable.",
      "The structural change is rhythm. The traditional cycle is episodic: data freezes at month-end, analysis runs over subsequent weeks, results are presented quarterly. The new rhythm is continuous — data observed daily, analyses weekly, deviations flagged in near-real-time — and the quarterly close becomes a confirmation rather than a discovery exercise. The methods do not change; they remain those of the actuarial syllabus. What changes is when the work happens and the cycle time between data and insight. The Casualty Actuarial Society and the Institute and Faculty of Actuaries have both issued discussion documents converging on documented assumptions, independent validation, and professional accountability retained by the named actuary.",
    ],
    closing:
      "The pattern in deployed systems is to use agents for assembly, monitoring, and drafting, and to preserve the methodological and judgement decisions explicitly with the actuary. The limitation that remains is that an agent cannot bear the professional liability the regulatory framework places on the appointed actuary; the chapters in Part V take up this constraint in detail.",
    pullQuote:
      "The quarterly scramble becomes a quarterly review.",
  },

  15: {
    vignette:
      "A pension consulting actuary is running the triennial valuations for fifty schemes, each with its own benefit structure, member data format, and assumption history. The actuarial work is identical in shape across schemes and idiosyncratic in detail. An agentic pipeline ingests the member data, applies the standard valuations, runs the prescribed sensitivity analyses, and produces draft reports tailored to each scheme's structure. The actuary reviews the unusual cases, signs the reports, and recovers the time previously spent on assembly.",
    summary: [
      "Life, health and pensions share a structural feature that makes them hospitable to agentic AI: the calculations are well-defined, the data flows repeatable, and the variation across cases sits in parameters and policy terms rather than in methods. The professional value lies in assumption-setting, judgement on emerging experience, and stakeholder communication. The clerical and analytical assembly surrounding those activities is what agentic AI compresses. Life product development illustrates the pattern — an agent that runs profit tests across assumption combinations, produces sensitivity tables and drafts supporting documentation reduces a development cycle from weeks to days, while the product actuary's judgement on which assumptions to test and how to communicate the result remains the centre of the work.",
      "Mortality and morbidity analysis is a continuous obligation, and an agent conducting the standard study against published tables — the Indian Assured Lives Mortality tables, SOA experience studies, the CMI tables in the United Kingdom — produces a draft assumption recommendation with unusual segments flagged for closer examination. Health insurance analytics monitors utilisation, treatment cost trends and case-mix shifts to support both pricing and the medical director's clinical review. Pension valuations have produced the cleanest efficiency gains in deployed systems: high-volume, structured and time-bound work where the actuary's review concentrates on the schemes that require judgement while routine cases pass through with confirmation rather than reconstruction. Asset-liability management benefits differently, from the ability to run more scenarios than the manual approach allowed.",
      "Policyholder communication is the application that most directly affects the policyholder experience — annual statements, benefit illustrations and disclosure documents, drafted against each policyholder's data, the regulatory requirements and the company's standards. Privacy and consent considerations here are the most demanding in the book. Health information is among the most sensitive data the industry handles, and GDPR in Europe, HIPAA in the United States and the Digital Personal Data Protection Act in India impose specific requirements. These systems are typically deployed within the insurer's own infrastructure or under contracts prohibiting secondary use, with identifiable elements redacted before processing where the analytical task does not require them.",
    ],
    closing:
      "Pensions has its own regulatory geometry, with the Pensions Regulator in the United Kingdom, the corresponding bodies in other jurisdictions, and the IFRS and accounting frameworks that govern reporting. Agentic AI in pensions is therefore deployed alongside the existing actuarial governance: signed valuations, documented assumptions, peer review, and the actuarial function holder's accountability. The technology supports the production of valuations; the professional architecture remains as it was.",
    pullQuote:
      "The routine cases pass through the pipeline with confirmation rather than reconstruction.",
  },

  16: {
    vignette:
      "A group chief risk officer faces a quarter in which IFRS 17 amendments, a Solvency II review consultation, and a domestic regulatory circular all land within six weeks of each other. Reading, summarising, and assessing impact across the group's businesses would consume two analysts for the quarter. A regulatory monitoring agent has already produced structured impact assessments, mapped to specific sections of the group's existing processes, with recommended actions ranked by materiality. The CRO's time is spent on the actions, not on the assessment.",
    summary: [
      "Risk and compliance face a structural challenge that intensifies year by year: the volume and velocity of regulatory change has outgrown the capacity of any reasonable team to monitor manually. The risk function has therefore been among the earliest sustained adopters of agentic AI in insurance. Regulatory monitoring is the canonical application — Solvency II, IFRS 17, LDTI under ASC 944, IRDAI circulars and the publications of the International Association of Insurance Supervisors each emit substantial document flows, and an agent that identifies material changes, summarises them in structured form and assesses relevance to existing processes produces a brief that previously required dedicated analyst time.",
      "Capital modelling support has produced measurable returns, assisting with parameter assembly, scenario specification and analytical exhibits while the methodology, assumptions and validation remain under the chief risk officer's and model risk function's control. Stress testing and scenario analysis have evolved alongside the regulatory expectation that they be more frequent, granular and integrated with strategic planning; the agent runs the models, while the choice of which scenarios to model and how to interpret them stays with the risk committee. ORSA production and board risk reporting are document-intensive activities where an agent drafts sections and assembles supporting analyses, compressing the production cycle without touching the substantive view of risk profile and capital adequacy. Model risk management is the application most directly aligned with the actuarial function's professional obligations, supporting a model inventory that has typically grown faster than the function's headcount.",
      "Auditability is a distinctive concern when agentic systems themselves operate in risk management. A regulatory tribunal asking how a decision was reached requires a record of the inputs, the model calls, the tool invocations and the human approvals that produced the output — structured logging and status fields, emitted by the system as it runs. That is a different artefact from the model's own account of its reasoning, which is generated narration and belongs to review rather than to evidence. Designing for that record from the beginning, rather than retrofitting it, is what separates deployable systems from undeployable ones. The constraints are severe and worth stating plainly: professional accountability sits with the chief risk officer, the actuarial function holder and the named professionals who sign reports, and no agent can absorb it. Systems that have been deployed successfully support those professionals without substituting for their judgement.",
    ],
    closing:
      "The capability is established and increasingly standard in larger insurers. The cycle time gains are real and large. The professional and regulatory architecture continues to evolve, but the direction of travel is settled: agentic AI is a productivity layer in modern risk management, governed under the existing framework rather than under a new one.",
    pullQuote:
      "The CRO's time is spent on the actions, not on the assessment.",
  },

  17: {
    vignette:
      "A pricing AI assistant performed beautifully in user acceptance testing and was deployed with care six months ago. Today it produced a recommendation that, on review, no qualified pricing actuary would have endorsed. The cause is not a single failure but a drift: the source data format changed slightly, a model upstream was updated by its provider, the prompt template was modified for an unrelated improvement, and no one connected the pieces. The system had no failure that triggered an alarm. It had a quiet degradation that no one was watching for.",
    summary: [
      "A working prototype shows the technology can do the task; a production deployment shows the team can sustain it over time, in changing conditions, with appropriate governance. The gap between the two is responsible for the majority of agentic AI projects that succeed in pilots and fail in operations. Reliability engineering comes first: acceptable output quality on the inputs actually received, latency within service level, throughput at peak load, and tolerance of upstream failures through retries with backoff, circuit breakers, fallback paths and graceful degradation. None of this is AI-specific; all of it is essential.",
      "Testing agentic systems is harder than testing deterministic ones because the same input can produce different outputs across runs. Three patterns have stabilised: unit testing of tools follows ordinary software practice; integration testing of agent flows uses scripted scenarios scored automatically against ground truth or by human evaluators; adversarial testing constructs inputs designed to expose failure modes. Human-in-the-loop design is the architectural pattern that made agentic AI deployable in regulated contexts at all — identify the points where errors would be consequential and require approval there. It works because most agentic errors are detectable by a qualified reviewer if surfaced; the failures occur when they are not. Monitoring extends testing into production, tracking latency per step, error rates by category, agent step counts, tool failure rates, token consumption and quality metrics, with alerting calibrated iteratively.",
      "Governance frameworks have begun to converge across the Actuarial Standards Board, the Institute and Faculty of Actuaries, the International Actuarial Association and the Casualty Actuarial Society on five elements: documented assumptions, validation evidence, ongoing production monitoring, clear professional accountability, and proportionality — rigour scaling with materiality. Professional codes apply unchanged: an actuary deploying an agentic system is responsible for its outputs to the same standard as manual work, and the code does not lower its standards in proportion to automation. Bias and fairness are acute, since a system reflecting historical patterns of unfair discrimination can perpetuate them. Change management is the part engineering discussions most underestimate — the deployment can succeed technically and fail organisationally without attention to training, role redefinition and team culture.",
    ],
    closing:
      "Production reliability metrics — uptime, latency percentiles, error rates, throughput — are the same metrics any production system reports. Quality metrics — output accuracy, hallucination rate, refusal rate where refusal is appropriate — are AI-specific and require deliberate measurement. An agentic system that lacks both is not, by any reasonable standard, in production.",
    pullQuote:
      "The professional code does not lower its standards in proportion to the level of automation.",
  },

  18: {
    vignette:
      "An actuarial student in 2030, in the final year of fellowship study, is preparing for a mortality study assignment. She is fluent in the methods, understands the assumptions, and is comfortable with the data. She is also comfortable directing an agentic system to perform the assembly, run the analysis, and produce the draft commentary. Her professional value lies in what she does after the agent completes its work: the judgement, the assumption-setting, the communication, the accountability. The shift is recognisable. The profession is recognisable. The toolkit has changed.",
    summary: [
      "The actuarial profession has reinvented itself many times — from the mortality tables of the seventeenth century through the establishment of the professional bodies in the nineteenth, the arrival of computers in the mid-twentieth, the integration of financial economics in the late twentieth, and the data-science extensions of the twenty-first. Each reinvention preserved the essential structure — quantitative analysis under uncertainty, in service of long-term financial promises, with personal professional accountability — while changing the toolkit. Agentic AI is the current reinvention: large enough to matter, not large enough to dissolve the profession. Multimodal models, reasoning models and computer-use agents each enlarge what is plausible; none changes the structural constraints on accountability.",
      "The skill set of a productive actuary now combines a technical core that has not moved — probability, statistics, financial mathematics, mortality, morbidity, reserving, capital, ALM — with data and AI competencies that have joined it, and strategic and interpersonal skills that were always there. The change is in proportion: analytical assembly has compressed, and the time freed has gone, where deployment has been thoughtful, to judgement work and stakeholder engagement. New roles have appeared in larger organisations — the actuarial AI engineer, the model risk specialist focused on AI components, the actuarially trained chief data and analytics officer — each adding an interface between traditional roles and the technical infrastructure. Headcount has been broadly stable, with redistribution rather than reduction; the forecast large workforce reductions have not materialised in the timescales predicted.",
      "Three scenarios for 2035 are worth holding without committing to any. The augmented actuary is the dominant pattern, with agentic AI handling analytical assembly while actuaries focus on judgement, assumption-setting, communication and accountability. The platform actuary is a smaller but strategically important fraction who become the designers, validators and governors of the systems performing actuarial work at scale — closer to a software architect, and in demand faster than supply. The diminished actuary is the scenario in which the profession treats AI as a foreign technology to be resisted and finds its work performed by data scientists without actuarial training. It is not the most likely outcome; it is possible, and it is what disengagement produces. Which prevails is a function of choices being made now.",
    ],
    closing:
      "The profession is not at risk from agentic AI. It is at risk only from the failure to adapt to it. The structural argument made in Chapter 1 — that no AI system can sign an actuarial opinion, bear professional liability, or be called before a tribunal under oath — places a permanent boundary on what the technology can do without the profession. The space within that boundary is enlarging, the analytical surface is growing richer, the cycle times are compressing.",
    pullQuote:
      "A profession reinvents itself collectively or it does not reinvent itself at all.",
  },
};

export function getChapterContent(n: number): ChapterContent | undefined {
  return CHAPTER_CONTENT[n];
}
